version: "3"
services:
  laravel-docker:
      container_name: helitech-app-docker
      build:
          context: .
          dockerfile: ./docker/php/Dockerfile
      expose:
          - 9000
      volumes:
          - .:/usr/src/app
          - ./public:/usr/src/app/public

      depends_on: helitech-db
      networks:
          - helitech_network





  helitech-db:
      container_name: helitech-db
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: helitech
        MYSQL_ROOT: root
        MYSQL_USER: root
        MYSQL_PASSWORD: admin123
      volumes:
          - ./storage/db-data:/var/lib/mysql
      ports:
          - 3307:3307
      networks:
          - helitech_network

networks:
    helitech_network:
        driver: bridge
