version: "3"
services:
  laravel-docker:
      container_name: helitech-app-docker
      build:
          context: .
          dockerfile: Dockerfile
      expose:
          - 9000
      volumes:
          - .:/usr/src/app
          - ./public:/usr/src/app/public
      depends_on:
          - helitech_db
      networks:
          - helitech_network

  helitech_db:
      container_name: helitech_db
      image: mysql:8.0.20
      restart: always
      volumes:
          - ./storage/db-data:/var/lib/mysql
      ports:
          - 3306:3306
      environment:
          MYSQL_DATABASE: helitech
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      networks:
          - helitech_network

networks:
    helitech_network:
        driver: bridge
